"""create reports table

Revision ID: d52200cd32cc
Revises: 926e03a1f9c1
Create Date: 2026-06-26 15:01:03.122505

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'd52200cd32cc'
down_revision: str | None = '926e03a1f9c1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('usuario_id', sa.Uuid(), nullable=False),
    sa.Column('repositorio_id', sa.Uuid(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('analise_id', sa.Uuid(), nullable=True),
    sa.Column('gerado_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('caminho_arquivo', sa.String(length=500), nullable=False),
    sa.ForeignKeyConstraint(['analise_id'], ['analyses.id'], ),
    sa.ForeignKeyConstraint(['repositorio_id'], ['repositories.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_repositorio_id'), 'reports', ['repositorio_id'], unique=False)
    op.create_index(op.f('ix_reports_usuario_id'), 'reports', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reports_usuario_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_repositorio_id'), table_name='reports')
    op.drop_table('reports')
    # ### end Alembic commands ###
